[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.14.0"
ic-cdk-macros = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
getrandom = { version = "0.2", default-features = false, features = ["custom"] }
rand = { version = "0.8", default-features = false, features = ["std"] }
ic-http-certification = "3.0"
ic-evm-utils = { version = "4.0.0", default-features = false }
primitive-types = "0.12"
ethabi = "18.0"
rlp = "0.5"
ethers-core = "2.0"
sha3 = "0.10" 
